version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    working_dir: /var/www
    ports:
      - "9000:9000"
    command: ["bash", "-c", "chown -R www-data:www-data /var/www/storage && chmod -R 775 /var/www/storage && php-fpm"]
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=homestead
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx-app:
    image: nginx:latest
    ports:
      - "9010:80"
    volumes:
    - ./nginx:/etc/nginx/conf.d
    - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
    enable_ipv6: false

volumes:
  db_data:

    driver: local

